version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.2-jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db

volumes:
  mongo:
    external: false
